deployment: basic_zenoh_interprocess
platforms:
  - name: vehicle1
    interfaces:
     - goby3_example_basic_zenoh_interprocess_publisher_interface.yml
     - goby3_example_basic_zenoh_interprocess_subscriber_interface.yml
