# Shared initialization for the Goby interprocess Julia example applications.
#
# This file lives one directory above each application's build output, so an
# application script (build/julia/<app>/<app>.jl) loads it with:
#   include(joinpath(@__DIR__, "..", "goby_application_init.jl"))
#
# It provides:
#   - an activated Goby.jl environment, with the Goby module loaded
#     (Goby.publish, Goby.subscribe, Goby.run, ...)
#   - init_cxxwrap(app_name), which loads the CxxWrap'd C++ application library
#     built alongside the script, adding the application's symbols to Goby
#     (e.g. Goby.BasicJuliaPublisher, Goby.INTERPROCESS, Goby.PROTOBUF, ...)
#   - include_protos(module, package), which loads the Julia Protobuf bindings
#     generated by protobuf_generate_julia() in CMake

using Pkg
Pkg.activate(joinpath(@__DIR__, "Goby.jl"), io=devnull)

using Goby

# Load lib<app_name>.so from the application's build directory into the Goby module
function init_cxxwrap(app_name)
    lib_path_expr = :(joinpath(@__DIR__, $app_name, "lib" * $app_name * ".so"))
    @eval Goby begin
        @wrapmodule(() -> $lib_path_expr)
        function __init__()
            @initcxx
        end
    end
end

# Load the generated Julia Protobuf bindings for `package` (the package name
# given to protobuf_generate_julia() in CMake) into `mod`, e.g.
#   include_protos(@__MODULE__, "goby3_examples")
# makes goby3_examples.protobuf.NavigationReport available.
function include_protos(mod::Module, package::AbstractString)
    Base.include(mod, joinpath(@__DIR__, package, package * ".jl"))
end
